<?php

namespace Azuriom\Plugin\ApexsionsBridge\Models;

use Illuminate\Database\Eloquent\Model;

class RankConfig extends Model
{
    protected $table = 'apexsions_rank_configs';

    protected $fillable = [
        'rank_key',
        'display_name',
        'badge',
        'prefix',
        'color',
        'tier',
        'weight',
        'order_index',
        'is_active',
        'is_buyable',
        'banner_image',
        'card_image',
        'description',
        'price_trial_30',
        'price_trial_90',
        'price_permanent',
        'price_upgrade_override',
        'discount_percent',
        'money_reward_permanent',
        'benefit_max_homes',
        'benefit_max_auctions',
        'benefit_max_enchants',
        'benefit_rtp_cooldown',
        'benefit_shop_sell_bonus',
        'benefit_xp_bonus',
        'benefit_bank_multiplier',
        'benefit_feed_cooldown',
        'benefit_commands',
        'benefit_kits',
        'benefit_nick_permission',
        'benefit_battlepass_unlock',
        'benefit_battlepass_discount',
    ];

    protected $casts = [
        'is_active' => 'boolean',
        'is_buyable' => 'boolean',
        'price_trial_30' => 'float',
        'price_trial_90' => 'float',
        'price_permanent' => 'float',
        'price_upgrade_override' => 'float',
        'discount_percent' => 'float',
        'money_reward_permanent' => 'float',
        'benefit_max_homes' => 'integer',
        'benefit_max_auctions' => 'integer',
        'benefit_max_enchants' => 'integer',
        'benefit_rtp_cooldown' => 'integer',
        'benefit_shop_sell_bonus' => 'float',
        'benefit_xp_bonus' => 'float',
        'benefit_bank_multiplier' => 'float',
        'benefit_feed_cooldown' => 'integer',
        'benefit_commands' => 'array',
        'benefit_kits' => 'array',
        'benefit_battlepass_discount' => 'float',
    ];

    /**
     * Seed or return default rank configurations if table is empty.
     */
    public static function seedDefaultsIfEmpty(): void
    {
        if (self::count() > 0) {
            return;
        }

        $defaults = [
            [
                'rank_key' => 'wanderer',
                'display_name' => 'Wanderer',
                'badge' => 'Wanderer',
                'prefix' => '[Wanderer] ',
                'color' => '#95a5a6',
                'tier' => 'Tier I',
                'weight' => 10,
                'order_index' => 1,
                'is_active' => true,
                'is_buyable' => false,
                'banner_image' => null,
                'card_image' => null,
                'description' => 'Fondasi peradaban Apexsions. Rank standar bagi setiap warga baru yang menjejakkan kaki di realm.',
                'price_trial_30' => 0,
                'price_trial_90' => 0,
                'price_permanent' => 0,
                'price_upgrade_override' => null,
                'money_reward_permanent' => 0,
                'benefit_max_homes' => 2,
                'benefit_max_auctions' => 3,
                'benefit_max_enchants' => 4,
                'benefit_rtp_cooldown' => 150, // 2m 30s
                'benefit_shop_sell_bonus' => 0.0,
                'benefit_xp_bonus' => 0.0,
                'benefit_bank_multiplier' => 1.0,
                'benefit_commands' => [],
                'benefit_kits' => [],
                'benefit_nick_permission' => 'none',
                'benefit_battlepass_unlock' => null,
                'benefit_battlepass_discount' => 0.0,
            ],
            [
                'rank_key' => 'ascendant',
                'display_name' => 'Ascendant',
                'badge' => '☘ ASCENDANT',
                'prefix' => '[☘ ASCENDANT] ',
                'color' => '#38ef7d',
                'tier' => 'Tier II',
                'weight' => 30,
                'order_index' => 2,
                'is_active' => true,
                'is_buyable' => true,
                'banner_image' => 'assets/themes/apexsions/img/package-ascendant.jpg',
                'card_image' => 'assets/themes/apexsions/img/package-ascendant.jpg',
                'description' => 'Awal kebangkitan peradaban. Tingkat pertama menuju strata kekuasaan yang lebih tinggi di Apexsions.',
                'price_trial_30' => 20000,
                'price_trial_90' => 45000,
                'price_permanent' => 65000,
                'price_upgrade_override' => null,
                'money_reward_permanent' => 50000,
                'benefit_max_homes' => 3,
                'benefit_max_auctions' => 4,
                'benefit_max_enchants' => 5,
                'benefit_rtp_cooldown' => 135, // 2m 15s
                'benefit_shop_sell_bonus' => 3.0,
                'benefit_xp_bonus' => 5.0,
                'benefit_bank_multiplier' => 1.0,
                'benefit_commands' => [],
                'benefit_kits' => ['Ascendant Kit'],
                'benefit_nick_permission' => 'none',
                'benefit_battlepass_unlock' => null,
                'benefit_battlepass_discount' => 0.0,
            ],
            [
                'rank_key' => 'archon',
                'display_name' => 'Archon',
                'badge' => '💎 ARCHON',
                'prefix' => '[💎 ARCHON] ',
                'color' => '#00c6ff',
                'tier' => 'Tier II',
                'weight' => 40,
                'order_index' => 3,
                'is_active' => true,
                'is_buyable' => true,
                'banner_image' => 'assets/themes/apexsions/img/package-archon.jpg',
                'card_image' => 'assets/themes/apexsions/img/package-archon.jpg',
                'description' => 'Otoritas dan kepemimpinan peradaban tingkat lanjut dengan kendali arsitektur dan kemudahan portabel.',
                'price_trial_30' => 40000,
                'price_trial_90' => 95000,
                'price_permanent' => 135000,
                'price_upgrade_override' => null,
                'money_reward_permanent' => 80000,
                'benefit_max_homes' => 4,
                'benefit_max_auctions' => 7,
                'benefit_max_enchants' => 6,
                'benefit_rtp_cooldown' => 120, // 2m
                'benefit_shop_sell_bonus' => 5.0,
                'benefit_xp_bonus' => 8.0,
                'benefit_bank_multiplier' => 1.2,
                'benefit_commands' => ['/craft', '/enderchest'],
                'benefit_kits' => ['Archon Kit'],
                'benefit_nick_permission' => 'none',
                'benefit_battlepass_unlock' => null,
                'benefit_battlepass_discount' => 0.0,
            ],
            [
                'rank_key' => 'sovereign',
                'display_name' => 'Sovereign',
                'badge' => '⚜ SOVEREIGN',
                'prefix' => '[⚜ SOVEREIGN] ',
                'color' => '#f1c40f',
                'tier' => 'Tier II',
                'weight' => 50,
                'order_index' => 4,
                'is_active' => true,
                'is_buyable' => true,
                'banner_image' => 'assets/themes/apexsions/img/package-sovereign.jpg',
                'card_image' => 'assets/themes/apexsions/img/package-sovereign.jpg',
                'description' => 'Kekuasaan ningrat dan kepemimpinan kerajaan penuh wibawa dengan kuasa menempa dan identitas nama.',
                'price_trial_30' => 75000,
                'price_trial_90' => 180000,
                'price_permanent' => 250000,
                'price_upgrade_override' => null,
                'money_reward_permanent' => 120000,
                'benefit_max_homes' => 5,
                'benefit_max_auctions' => 10,
                'benefit_max_enchants' => 8,
                'benefit_rtp_cooldown' => 95, // 1m 35s
                'benefit_shop_sell_bonus' => 8.0,
                'benefit_xp_bonus' => 10.0,
                'benefit_bank_multiplier' => 1.5,
                'benefit_commands' => ['/craft', '/anvil', '/smithing', '/enderchest'],
                'benefit_kits' => ['Sovereign Kit'],
                'benefit_nick_permission' => 'no_color', // /nick tanpa edit warna
                'benefit_battlepass_unlock' => null,
                'benefit_battlepass_discount' => 0.0,
            ],
            [
                'rank_key' => 'emperor',
                'display_name' => 'Emperor',
                'badge' => '⚔ EMPEROR',
                'prefix' => '[⚔ EMPEROR] ',
                'color' => '#e52d27',
                'tier' => 'Tier II',
                'weight' => 60,
                'order_index' => 5,
                'is_active' => true,
                'is_buyable' => true,
                'banner_image' => 'assets/themes/apexsions/img/package-emperor.jpg',
                'card_image' => 'assets/themes/apexsions/img/package-emperor.jpg',
                'description' => 'Kaisar terhormat dengan supremasi tak terbantahkan, hak reparasi peradaban, dan akses langsung Sio Pass.',
                'price_trial_30' => 135000,
                'price_trial_90' => 320000,
                'price_permanent' => 450000,
                'price_upgrade_override' => null,
                'money_reward_permanent' => 180000,
                'benefit_max_homes' => 7,
                'benefit_max_auctions' => 14,
                'benefit_max_enchants' => 11,
                'benefit_rtp_cooldown' => 70, // 1m 10s
                'benefit_shop_sell_bonus' => 12.0,
                'benefit_xp_bonus' => 14.0,
                'benefit_bank_multiplier' => 2.0,
                'benefit_feed_cooldown' => 300, // 5m
                'benefit_commands' => ['/craft', '/anvil', '/smithing', '/repair', '/feed', '/hat', '/enderchest'],
                'benefit_kits' => ['Emperor Kit'],
                'benefit_nick_permission' => 'solid_color', // Warna solid, tanpa gradient
                'benefit_battlepass_unlock' => 'sio',
                'benefit_battlepass_discount' => 10.0,
            ],
            [
                'rank_key' => 'sions',
                'display_name' => 'Sions',
                'badge' => '✦ SIONS ✦',
                'prefix' => '[✦ SIONS] ',
                'color' => '#00FFFF',
                'tier' => 'Tier II',
                'weight' => 70,
                'order_index' => 6,
                'is_active' => true,
                'is_buyable' => true,
                'banner_image' => 'assets/themes/apexsions/img/package-sions.jpg',
                'card_image' => 'assets/themes/apexsions/img/package-sions.jpg',
                'description' => 'Puncak kedaulatan peradaban Apexsions. Privilese mutlak, RTP kilat, seluruh warna nama, serta seluruh season pass terbuka.',
                'price_trial_30' => 225000,
                'price_trial_90' => 550000,
                'price_permanent' => 800000,
                'price_upgrade_override' => null,
                'money_reward_permanent' => 300000,
                'benefit_max_homes' => 10,
                'benefit_max_auctions' => 20,
                'benefit_max_enchants' => 15,
                'benefit_rtp_cooldown' => 50, // 50s
                'benefit_shop_sell_bonus' => 17.0,
                'benefit_xp_bonus' => 20.0,
                'benefit_bank_multiplier' => 3.0,
                'benefit_feed_cooldown' => 180, // 3m
                'benefit_commands' => ['/craft', '/anvil', '/smithing', '/repair', '/feed', '/hat', '/enderchest'],
                'benefit_kits' => ['Sions Kit'],
                'benefit_nick_permission' => 'all_colors', // Semua warna & gradient
                'benefit_battlepass_unlock' => 'exsio', // Membuka Exsio dan Sio Pass
                'benefit_battlepass_discount' => 15.0,
            ],
        ];

        foreach ($defaults as $data) {
            self::updateOrCreate(['rank_key' => $data['rank_key']], $data);
        }
    }
}
