# ============================================================
# APEXSIONS: SIONS ANCIENT KEYS & VAULT TOKENS
# ============================================================

SionsCommonKey:
  Id: TRIPWIRE_HOOK
  Display: '<gradient:#bdc3c7:#7f8c8d><bold>Kunci Kuno Sions</bold></gradient>'
  Lore:
    - '<gray>Kunci perunggu berkarat yang diselubungi</gray>'
    - '<gray>energi samar reruntuhan masa lampau.</gray>'
    - ''
    - '<yellow>Tingkat:</yellow> <white>Biasa (Common)</white>'
    - '<yellow>Kegunaan:</yellow> <gray>Membuka Peti & Tong Reruntuhan Sions</gray>'
    - ''
    - '<dark_gray>Drop dari pasukan jelata reruntuhan Sions.</dark_gray>'
  NBT:
    sions_key: 'common'
  CustomModelData: 1001

SionsEliteKey:
  Id: AMETHYST_SHARD
  Display: '<gradient:#f1c40f:#d35400><bold>Kunci Khazanah Ksatria Sions</bold></gradient>'
  Lore:
    - '<gold>Kunci kristal berkilauan yang ditempa</gold>'
    - '<gold>oleh para ksatria pelindung imperium.</gold>'
    - ''
    - '<yellow>Tingkat:</yellow> <gold><bold>Elit (Elite)</bold></gold>'
    - '<yellow>Kegunaan:</yellow> <gray>Membuka Peti Jebakan & Khazanah Ksatria</gray>'
    - ''
    - '<dark_purple>Drop dari Ksatria & Ruin Sentinel Sions.</dark_purple>'
  NBT:
    sions_key: 'elite'
  CustomModelData: 1002

SionsBossKey:
  Id: ECHO_SHARD
  Display: '<gradient:#9b59b6:#e74c3c><bold>Kunci Void Kaisar Valerius</bold></gradient>'
  Lore:
    - '<dark_purple>Kunci pusaka Tahta Valerius yang bergetar</dark_purple>'
    - '<dark_purple>memancarkan resonansi Celah Kegelapan Umbra.</dark_purple>'
    - ''
    - '<yellow>Tingkat:</yellow> <light_purple><bold>Kaisar (Raid Boss Tier)</bold></light_purple>'
    - '<yellow>Kegunaan:</yellow> <gray>Membuka Peti Shulker Pusaka Tahta Kaisar</gray>'
    - ''
    - '<red><bold>Dijamin drop dari Kaisar Valerius (100%).</bold></red>'
  NBT:
    sions_key: 'boss'
  CustomModelData: 1003
