#!/usr/bin/env python3
# Server console-executable commands catalog (WorldEdit and player-only strictly purged)

SERVER_COMMANDS = {
    "advancement": "A Mojang provided command.",
    "ajleaderboards": "Commands for ajLeaderboards",
    "allowfire": "[<world>] - Allows all fire spread temporarily",
    "apexenchant": "Alias for /enchant.",
    "apexionscore": "Alias for ApexsionsCore admin management.",
    "apexsionschat": "ApexsionsChat chat moderation and management",
    "apexsionscore": "ApexsionsCore administration and inspection",
    "apexsionseconomy": "ApexsionsEconomy currency and transaction management",
    "apexsionsshop": "ApexsionsShop configuration reload",
    "attribute": "A Mojang provided command.",
    "authme": "AuthMe player account and security administration",
    "backup": "Runs the backup if configured.",
    "balancetop": "Gets the top balance values.",
    "ban": "Bans a player.",
    "ban-ip": "A Mojang provided command.",
    "banip": "Bans an IP address.",
    "bluemap": "bluemap:",
    "bossbar": "Manage custom Minecraft bossbars",
    "broadcast": "Broadcasts a message to the entire server.",
    "broadcastworld": "Broadcasts a message to a world.",
    "bukkit": "version: Gets the version of this server including any plugins in use",
    "burn": "Set a player on fire.",
    "butcher": "Kill all or nearby mobs",
    "chunky": "Generates chunks",
    "citizens": "Administration commands",
    "clone": "A Mojang provided command.",
    "cracked": "Label the invoker or the player specified as cracked if marked premium before",
    "crate": "ApexsionsCrates key administration",
    "customenchant": "Alias for /enchant.",
    "damage": "A Mojang provided command.",
    "data": "A Mojang provided command.",
    "datapack": "A Mojang provided command.",
    "debug": "A Mojang provided command.",
    "decentholograms": "The main DecentHolograms Command.",
    "defaultgamemode": "A Mojang provided command.",
    "deljail": "Removes a jail.",
    "delkit": "Deletes the specified kit.",
    "deop": "A Mojang provided command.",
    "difficulty": "A Mojang provided command.",
    "eco": "Manages the server economy.",
    "ecoadmin": "Admin economy management command",
    "ecobridge": "",
    "economy": "Main command for Apexsions Economy",
    "effect": "A Mojang provided command.",
    "enchant": "Enchants the item the user is holding.",
    "execute": "A Mojang provided command.",
    "exp": "Give, set, reset, or look at a players experience.",
    "experience": "A Mojang provided command.",
    "fastlogin": "Label the invoker as premium",
    "feature": "Generate Minecraft features",
    "fill": "A Mojang provided command.",
    "fillbiome": "A Mojang provided command.",
    "filter": "Add or remove programmable filters to the packet listeners.",
    "floodgate": "A set of Floodgate related actions in one command",
    "forceload": "A Mojang provided command.",
    "function": "A Mojang provided command.",
    "fwhitelist": "Easy way to whitelist Bedrock players",
    "gamemode": "Change player gamemode.",
    "gamerule": "A Mojang provided command.",
    "gc": "Reports memory, uptime and tick info.",
    "geyser": "Geyser Bedrock bridge administration",
    "geyser-spigot": "Geyser Bedrock bridge administration",
    "give": "Give a player an item.",
    "halt-activity": "[confirm] - Attempts to cease as much activity in order to stop lag",
    "help": "Views a list of available commands.",
    "imageframe": "Plugin main command",
    "jailedplayers": "List all jailed players.",
    "jails": "List all jails.",
    "jfr": "A Mojang provided command.",
    "jm": "A Mojang provided command.",
    "kick": "Kicks a specified player with a reason.",
    "kickall": "Kicks all players off the server except the issuer.",
    "kill": "Kills specified player.",
    "kingdom": "Realm / Kingdom navigation, selection, and information.",
    "kingdomcore": "Legacy alias for ApexsionsCore admin management.",
    "kit": "Obtains the specified kit or views all available kits.",
    "kitreset": "Resets the cooldown on the specified kit.",
    "list": "List all online players.",
    "locate": "[player] - Locate a player",
    "loot": "A Mojang provided command.",
    "luckperms": "Manage permissions",
    "maintenance": "Server Maintenance Mode management.",
    "media": "Master command for creating and managing interactive media banners.",
    "minecraft": "xp: A Mojang provided command.",
    "msg": "Sends a private message to the specified player.",
    "mspt": "View server tick times",
    "mv": "",
    "mvsetspawn": "Sets the spawn location of the specified world",
    "mvspawn": "Teleports the specified player to the spawn of the world they are in",
    "mvtp": "Allows you to teleport to a location on your server!",
    "mythicmobs": "spawnmob: Spawn a mob",
    "nick": "Change your nickname or that of another player.",
    "nightcore": "Nightcore core engine commands",
    "npc": "Basic commands for all NPC-related things",
    "op": "A Mojang provided command.",
    "packet": "Add or remove a simple packet listener.",
    "packetlog": "Logs hex representations of packets to a file or console",
    "paper": "Paper server metrics and configuration",
    "pardon-ip": "A Mojang provided command.",
    "particle": "A Mojang provided command.",
    "perf": "A Mojang provided command.",
    "pl": "Gets a list of plugins running on the server",
    "place": "A Mojang provided command.",
    "placeholderapi": "PlaceholderAPI Command",
    "playsound": "A Mojang provided command.",
    "plugins": "Gets a list of plugins running on the server",
    "protocol": "Performs administrative tasks regarding ProtocolLib.",
    "random": "A Mojang provided command.",
    "region": "Region management commands",
    "registry": "Search through the given registry",
    "reload": "A Mojang provided command.",
    "remove": "Remove all entities of a type",
    "restart": "Restarts the server",
    "save-all": "A Mojang provided command.",
    "save-off": "A Mojang provided command.",
    "save-on": "A Mojang provided command.",
    "say": "A Mojang provided command.",
    "sb": "Scoreboard management",
    "schedule": "A Mojang provided command.",
    "scoreboard": "A Mojang provided command.",
    "seed": "A Mojang provided command.",
    "setblock": "A Mojang provided command.",
    "setidletimeout": "A Mojang provided command.",
    "setworldspawn": "A Mojang provided command.",
    "setworth": "Set the sell value of an item.",
    "shopadmin": "Menu Admin Toko Kerajaan Apexsions",
    "sions": "Sions Temporal Reconstruction administration and control.",
    "skin": "Changes your own skin.",
    "skript": "Skript's main command. Type '/skript help' for more information.",
    "slay": "[player] - Slay a player",
    "spark": "Spark server profiler and performance analysis",
    "spawnpoint": "A Mojang provided command.",
    "spigot": "Spigot related commands",
    "spreadplayers": "A Mojang provided command.",
    "sr": "Admin commands for SkinsRestorer.",
    "stop": "A Mojang provided command.",
    "stopfire": "[<world>] - Disables all fire spread temporarily",
    "stopsound": "A Mojang provided command.",
    "stopwatch": "A Mojang provided command.",
    "structure": "Generate Minecraft structures",
    "sudo": "Make another user perform a command.",
    "summon": "A Mojang provided command.",
    "sync": "Synchronize player profile, balances, and BattlePass with web platform.",
    "tab": "Plugin's main command",
    "team": "A Mojang provided command.",
    "tellraw": "A Mojang provided command.",
    "tempbanip": "Temporarily ban an IP Address.",
    "test": "A Mojang provided command.",
    "thunder": "Enable/disable thunder.",
    "tick": "A Mojang provided command.",
    "time": "Display/Change the world time. Defaults to current world.",
    "timings": "Manages Spigot Timings data to see performance of the server.",
    "togglejail": "Jails/Unjails a player, TPs them to the jail specified.",
    "tp": "Teleport to a player.",
    "tps": "Gets the current ticks per second for the server",
    "unban": "Unbans the specified player.",
    "unbanip": "Unbans the specified IP address.",
    "ver": "Gets the version of this server including any plugins in use",
    "version": "Gets the version of this server including any plugins in use",
    "viaversion": "Shows ViaVersion Version and more.",
    "voicechat": "Manage voice chat",
    "weather": "Sets the weather.",
    "whitelist": "A Mojang provided command.",
    "worldborder": "A Mojang provided command.",
    "worldguard": "WorldGuard commands",
}
