#!/usr/bin/env python3
# Complete catalog of all registered plugin commands extracted from server

SERVER_COMMANDS = {
    ".s": "Execute last CraftScript",
    "calculate": "Evaluate a mathematical expression",
    "center": "Set the center block(s)",
    "chunk": "Set the selection to your current chunk.",
    "cone": "Generates a cone.",
    "contract": "Contract the selection area",
    "copy": "Copy the selection to the clipboard",
    "count": "Counts the number of blocks matching a mask",
    "curve": "Draws a spline through selected points",
    "cut": "Cut the selection to the clipboard",
    "cyl": "Generates a cylinder.",
    "deform": "Deforms a selected region with an expression",
    "distr": "Get the distribution of blocks in the selection",
    "drain": "Drain a pool",
    "drawsel": "Toggle drawing the current selection",
    "expand": "Expand the selection area",
    "faces": "Build the walls, ceiling, and floor of a selection",
    "fast": "Toggle fast mode",
    "feature": "Generate Minecraft features",
    "fill": "A Mojang provided command.",
    "fillr": "Fill a hole recursively",
    "flip": "Flip the contents of the clipboard across the origin",
    "flora": "Make flora within the region",
    "forest": "Make a forest within the region",
    "generate": "Generates a shape according to a formula.",
    "generatebiome": "Sets biome according to a formula.",
    "hcyl": "Generates a hollow cylinder.",
    "help": "Views a list of available commands.",
    "hollow": "Hollows out the object contained in this selection",
    "hpos1": "Set position 1 to targeted block",
    "hpos2": "Set position 2 to targeted block",
    "hpyramid": "Generate a hollow pyramid",
    "hsphere": "Generates a hollow sphere.",
    "inset": "Inset the selection area",
    "limit": "Modify block change limit",
    "line": "Draws line segments between cuboid selection corners or convex polyhedral selection vertices",
    "move": "Move the contents of the selection",
    "naturalize": "3 layers of dirt on top then rock below",
    "outset": "Outset the selection area",
    "overlay": "Set a block on top of blocks in the region",
    "paste": "Paste the clipboard's contents",
    "perf": "A Mojang provided command.",
    "pos": "Set positions",
    "pos1": "Set position 1",
    "pos2": "Set position 2",
    "pyramid": "Generate a filled pyramid",
    "regen": "Regenerates the contents of the selection",
    "registry": "Search through the given registry",
    "reorder": "Sets the reorder mode of WorldEdit",
    "replace": "Replace all blocks in the selection with another",
    "replacebiome": "Replaces the biome of your current block or region.",
    "revolve": "Revolve the selection around a vertical axis",
    "rotate": "A Mojang provided command.",
    "sel": "Choose a region selector",
    "set": "Sets all the blocks in the region",
    "setbiome": "Sets the biome of your current block or region.",
    "shift": "Shift the selection area",
    "size": "Set the brush size",
    "smooth": "Smooth the elevation in the selection",
    "snowsmooth": "Smooth the elevation in the selection with snow layers",
    "sphere": "Generates a filled sphere.",
    "stack": "Stack items",
    "structure": "Generate Minecraft structures",
    "timeout": "Modify evaluation timeout time.",
    "trim": "Minimize the selection to encompass matching blocks",
    "update": "Apply side effects to your selection",
    "walls": "Build the four sides of the selection",
    "wand": "Get the wand item",
    "watchdog": "Changes watchdog hook state.",
    "world": "Switch between worlds.",
    "aadmin": "Open the Centralized Master Admin Hub for all Apexsions plugins.",
    "abp": "Admin BattlePass Control Panel",
    "ace": "Buka Admin Hub GUI untuk kontrol penuh sihir custom, katalog, creator, dan pricing.",
    "addpin": "quickly adds a pin",
    "admingui": "Open the Centralized Master Admin Hub for all Apexsions plugins.",
    "advancement": "A Mojang provided command.",
    "afk": "Marks you as away-from-keyboard.",
    "ah": "Open the Auction House",
    "ajleaderboards": "Commands for ajLeaderboards",
    "allowfire": "[<world>] - Allows all fire spread temporarily",
    "antioch": "A little surprise for operators.",
    "anvil": "Opens up an anvil.",
    "apexadmin": "Open the Centralized Master Admin Hub for all Apexsions plugins.",
    "apexenchant": "Alias for /enchant.",
    "apexionscore": "Alias for ApexsionsCore admin management.",
    "apexsionschat": "realname: Resolve the real player account behind any active nickname.",
    "apexsionscore": "warp: Open warp navigation GUI or teleport to a specific warp location.",
    "apexsionseconomy": "pay: Transfer currency to another player",
    "apexsionsshop": "sell: Membuka GUI Penjualan Cepat Item",
    "ascend": "Go up a floor",
    "attribute": "A Mojang provided command.",
    "authme": "verification: Verification command",
    "axiompaper": "axiompapermigrateconfig:",
    "axiompaperdebug": "",
    "axiompapermigrateconfig": "",
    "back": "Teleports you to your location prior to tp/spawn/warp.",
    "backup": "Runs the backup if configured.",
    "balance": "States the current balance of a player.",
    "balancetop": "Gets the top balance values.",
    "ban": "Bans a player.",
    "ban-ip": "A Mojang provided command.",
    "banip": "Bans an IP address.",
    "beezooka": "Throw an exploding bee at your opponent.",
    "bigtree": "Spawn a big tree where you are looking.",
    "biomeinfo": "Get the biome of the targeted block.",
    "biomelist": "Gets all biomes available.",
    "bluemap": "bluemap:",
    "bmarker": "A command by the BMMarker plugin.",
    "bmarker-setup": "A command by the BMMarker plugin.",
    "bmarker-setup-set": "A command by the BMMarker plugin.",
    "bmmarker": "btp: A command by the BMMarker plugin.",
    "book": "Allows reopening and editing of sealed books.",
    "bossbar": "",
    "bottom": "Teleport to the lowest block at your current position.",
    "bounty": "Sistem hadiah kepala (bounty) antar pemain dan papan buronan.",
    "bp": "Main player command for Apexsions Battlepass",
    "bplayer": "A command by the BMMarker plugin.",
    "break": "Breaks the block you are looking at.",
    "broadcast": "Broadcasts a message to the entire server.",
    "broadcastworld": "Broadcasts a message to a world.",
    "brush": "Brushing commands",
    "bsettings": "A command by the BMMarker plugin.",
    "btemplate": "A command by the BMMarker plugin.",
    "btp": "A command by the BMMarker plugin.",
    "bukkit": "version: Gets the version of this server including any plugins in use",
    "burn": "Set a player on fire.",
    "butcher": "Kill all or nearby mobs",
    "captcha": "Captcha command",
    "caravan": "Buka pasar gelap kafilah keliling dan lihat status kemunculannya.",
    "cartographytable": "Opens up a cartography table.",
    "ce": "Buka Enchanter Gacha GUI dan Toko Buku Spesifik.",
    "ceil": "Go to the ceiling",
    "changepassword": "Change password of an account",
    "channel": "Switch or speak in a specific chat channel.",
    "chunkinfo": "Get information about the chunk you're inside",
    "chunky": "Generates chunks",
    "citizens": "Administration commands",
    "claim": "Sovereign land claiming and territory management.",
    "claiminfo": "View claim information and display visual particle boundaries.",
    "clearclipboard": "Clear your clipboard",
    "clearhistory": "Clear your history",
    "clearinventory": "Clear all items in your inventory.",
    "clearinventoryconfirmtoggle": "Toggles whether you are prompted to confirm inventory clears.",
    "clone": "A Mojang provided command.",
    "compass": "Describes your current bearing.",
    "condense": "Condenses items into a more compact blocks.",
    "cosmetics": "Open the Particle Cosmetics GUI for Head Auras, Footstep Trails, and Kill Effects.",
    "cracked": "Label the invoker or the player specified as cracked if marked premium before",
    "crate": "",
    "crateshop": "Buka Toko Pembelian Crate Keys Resmi Apexsions.",
    "crawl": "Merangkak menembus lubang 1 blok.",
    "createkit": "Create a kit in game!",
    "creator": "Master command for Content Creator verification, linking, video submit, and rewards.",
    "cs": "Execute a CraftScript",
    "customenchant": "Alias for /enchant.",
    "customtext": "Allows you to create custom text commands.",
    "cycler": "Block data cycler tool",
    "damage": "A Mojang provided command.",
    "data": "A Mojang provided command.",
    "datapack": "A Mojang provided command.",
    "deathcoords": "Lihat koordinat lokasi kematian terakhir dan panduan navigasi kompas.",
    "debug": "A Mojang provided command.",
    "decentholograms": "The main DecentHolograms Command.",
    "defaultgamemode": "A Mojang provided command.",
    "delchunks": "Delete chunks that your selection includes",
    "delhome": "Removes a home.",
    "deljail": "Removes a jail.",
    "delkit": "Deletes the specified kit.",
    "deltree": "Floating tree remover tool",
    "delwarp": "Deletes the specified warp.",
    "deop": "A Mojang provided command.",
    "deposit": "Setor cepat item inventory yang cocok ke peti yang sedang dibuka.",
    "depth": "States current depth, relative to sea level.",
    "descend": "Go down a floor",
    "dialog": "A Mojang provided command.",
    "difficulty": "A Mojang provided command.",
    "disposal": "Opens a portable disposal menu.",
    "eco": "Manages the server economy.",
    "ecoadmin": "Admin economy management command",
    "ecobridge": "",
    "economy": "Main command for Apexsions Economy",
    "editsign": "Edits a sign in the world.",
    "effect": "A Mojang provided command.",
    "email": "Add email or recover password",
    "enchant": "Enchants the item the user is holding.",
    "enderchest": "Lets you see inside an enderchest.",
    "essentials": "tree: Spawn a tree where you are looking.",
    "execute": "A Mojang provided command.",
    "exp": "Give, set, reset, or look at a players experience.",
    "experience": "A Mojang provided command.",
    "ext": "Extinguish players.",
    "extinguish": "Extinguish nearby fire",
    "farwand": "Wand at a distance tool",
    "fastlogin": "Label the invoker as premium",
    "feed": "Satisfy the hunger.",
    "fetchprofile": "A Mojang provided command.",
    "fillbiome": "A Mojang provided command.",
    "filter": "Add or remove programmable filters to the packet listeners.",
    "fireball": "Throw a fireball or other assorted projectiles.",
    "firework": "Allows you to modify a stack of fireworks.",
    "fish": "Menu utama peradaban memancing Apexsions",
    "fixlava": "Fix lava to be stationary",
    "fixwater": "Fix water to be stationary",
    "fldelete": "Delete player profile data",
    "floodfill": "Flood fill tool",
    "floodgate": "A set of Floodgate related actions in one command",
    "fly": "Take off, and soar!",
    "forceload": "A Mojang provided command.",
    "forestgen": "Generate a forest",
    "freemium": "Disable premium mode",
    "function": "A Mojang provided command.",
    "fwhitelist": "Easy way to whitelist Bedrock players",
    "gamemode": "Change player gamemode.",
    "gamerule": "A Mojang provided command.",
    "gc": "Reports memory, uptime and tick info.",
    "getpos": "Get your current coordinates or those of a player.",
    "geyser": "",
    "geyser-spigot": "geyser:",
    "give": "Give a player an item.",
    "global": "Switch to or speak in Global chat.",
    "gmask": "Set the global mask",
    "god": "Enables your godly powers.",
    "grave": "Ambil kembali item & XP dari nisan kematian Anda.",
    "green": "Converts dirt to grass blocks in the area",
    "grindstone": "Opens up a grindstone.",
    "halt-activity": "[confirm] - Attempts to cease as much activity in order to stop lag",
    "hat": "Get some cool new headgear.",
    "heal": "Heals you or the given player.",
    "helpop": "Message online admins.",
    "home": "Teleport to your home.",
    "ice": "Cools a player off.",
    "ignore": "Ignore or unignore other players.",
    "imageframe": "Plugin main command",
    "info": "Block information tool",
    "invsee": "See the inventory of other players.",
    "item": "Spawn an item.",
    "itemdb": "Searches for an item.",
    "itemlore": "Edit the lore of an item.",
    "itemname": "Names an item.",
    "jailedplayers": "List all jailed players.",
    "jails": "List all jails.",
    "jfr": "A Mojang provided command.",
    "jm": "A Mojang provided command.",
    "jump": "Jumps to the nearest block in the line of sight.",
    "jumpto": "Teleport to a location",
    "kick": "Kicks a specified player with a reason.",
    "kickall": "Kicks all players off the server except the issuer.",
    "kill": "Kills specified player.",
    "kingdom": "Realm / Kingdom navigation, selection, and information.",
    "kingdomchat": "Switch to or speak in Kingdom chat.",
    "kingdomcore": "Legacy alias for ApexsionsCore admin management.",
    "kit": "Obtains the specified kit or views all available kits.",
    "kitadmin": "Open the interactive Admin Kit Management GUI.",
    "kitreset": "Resets the cooldown on the specified kit.",
    "kits": "Open the Kingdom Kits menu to claim or preview equipment sets.",
    "kittycannon": "Throw an exploding kitten at your opponent.",
    "lay": "Berbaring / tiduran di lantai.",
    "level": "View character profile, level progression, rewards, and XP guide.",
    "lightning": "The power of Thor. Strike at cursor or player.",
    "link": "Link in-game Minecraft account to Apexsions web platform.",
    "linkaccount": "Link your Java account with your Bedrock account",
    "list": "List all online players.",
    "listchunks": "List chunks that your selection includes",
    "lobby": "Teleport to the main server lobby.",
    "locate": "[player] - Locate a player",
    "login": "Login command",
    "logout": "Logout command",
    "loom": "Opens up a loom.",
    "loot": "A Mojang provided command.",
    "lrbuild": "Long-range building tool",
    "luckperms": "Manage permissions",
    "mail": "Manages inter-player, intra-server mail.",
    "maintenance": "Server Maintenance Mode management.",
    "mask": "Set the brush mask",
    "material": "Set the brush material",
    "me": "Describes an action in the context of the player.",
    "media": "Master command for creating and managing interactive media banners.",
    "minecraft": "xp: A Mojang provided command.",
    "more": "Fills the item stack in hand to specified amount, or to maximum size if none is specified.",
    "motd": "Views the Message Of The Day.",
    "msg": "Sends a private message to the specified player.",
    "msgtoggle": "Blocks receiving all private messages.",
    "mspt": "View server tick times",
    "mute": "Mutes or unmutes a player.",
    "mv": "",
    "mvcd": "",
    "mvp": "",
    "mvsetspawn": "Sets the spawn location of the specified world",
    "mvspawn": "Teleports the specified player to the spawn of the world they are in",
    "mvtp": "Allows you to teleport to a location on your server!",
    "mythicmobs": "spawnmob: Spawn a mob",
    "mythicmobsmenu": "MythicMobs menu command",
    "navwand": "Navigation wand tool",
    "near": "Lists the players near by or around a player.",
    "nick": "Change your nickname or that of another player.",
    "nightcore": "",
    "none": "Unbind a bound tool from your current item",
    "npc": "Basic commands for all NPC-related things",
    "nuke": "May death rain upon them.",
    "op": "A Mojang provided command.",
    "packet": "Add or remove a simple packet listener.",
    "packetlog": "Logs hex representations of packets to a file or console",
    "paper": "spark:",
    "pardon-ip": "A Mojang provided command.",
    "particle": "A Mojang provided command.",
    "pay": "Pays another player from your balance.",
    "payconfirmtoggle": "Toggles whether you are prompted to confirm payments.",
    "paytoggle": "Toggles whether you are accepting payments.",
    "ping": "Pong!",
    "pins": "Easier command for pins",
    "pl": "Gets a list of plugins running on the server",
    "place": "A Mojang provided command.",
    "placeholderapi": "PlaceholderAPI Command",
    "placement": "Select which placement to use",
    "playsound": "A Mojang provided command.",
    "playtime": "Shows a player's time played in game",
    "plugins": "Gets a list of plugins running on the server",
    "pose": "Kelola pose dan emote karakter (sit, lay, crawl, bellyflop, spin, stand).",
    "potion": "Adds custom potion effects to a potion.",
    "powertool": "Assigns a command to the item in hand.",
    "powertoollist": "Lists all current powertools.",
    "powertooltoggle": "Enables or disables all current powertools.",
    "presets": "Buka menu preset armor & tool set yang tersimpan.",
    "protocol": "Performs administrative tasks regarding ProtocolLib.",
    "ptime": "Adjust player's client time. Add @ prefix to fix.",
    "pumpkins": "Generate pumpkin patches",
    "pweather": "Adjust a player's weather",
    "r": "Quickly reply to the last player to message you.",
    "random": "A Mojang provided command.",
    "range": "Set the brush range",
    "rank": "Open the interactive Rank Hierarchy and Donator Perks menu.",
    "ranks": "Open the interactive Rank Hierarchy and Donator Perks menu.",
    "realname": "Displays the username of a user based on nick.",
    "recipe": "Displays how to craft items.",
    "redo": "Redoes the last action (from history)",
    "region": "Region management commands",
    "register": "Register an account",
    "reload": "A Mojang provided command.",
    "remove": "Remove all entities of a type",
    "removeabove": "Remove blocks above your head.",
    "removebelow": "Remove blocks below you.",
    "removenear": "Remove blocks near you.",
    "renamehome": "Renames a home.",
    "repair": "Repairs the durability of one or all items.",
    "repl": "Block replacer tool",
    "replacenear": "Replace nearby blocks",
    "report": "Report a player for breaking server rules.",
    "reports": "View and manage in-server moderation reports.",
    "rest": "Rests you or the given player.",
    "restart": "Restarts the server",
    "restore": "Restore the selection from a snapshot",
    "ride": "A Mojang provided command.",
    "rtoggle": "Change whether the recipient of the reply is last recipient or last sender",
    "rtp": "Random teleport strictly inside your pledged kingdom territory.",
    "rules": "Views the server rules.",
    "save-all": "A Mojang provided command.",
    "save-off": "A Mojang provided command.",
    "save-on": "A Mojang provided command.",
    "say": "A Mojang provided command.",
    "sb": "",
    "schedule": "A Mojang provided command.",
    "schematic": "Schematic commands for saving/loading areas",
    "scoreboard": "A Mojang provided command.",
    "searchitem": "Search for an item",
    "seed": "A Mojang provided command.",
    "seen": "Shows the last logout time of a player.",
    "sell": "Sells the item currently in your hand.",
    "selwand": "Selection wand tool",
    "setblock": "A Mojang provided command.",
    "sethome": "Set your home to your current location.",
    "setidletimeout": "A Mojang provided command.",
    "setjail": "Creates a jail where you specified named [jailname].",
    "setspawn": "Sets the spawn point to your current position.",
    "settpr": "Set the random teleport location and parameters.",
    "setwarp": "Creates a new warp.",
    "setworldspawn": "A Mojang provided command.",
    "setworth": "Set the sell value of an item.",
    "shop": "Membuka Menu Pasar & Toko Kerajaan Apexsions",
    "shopadmin": "Menu Admin Toko Kerajaan Apexsions",
    "showitem": "Showcase the item currently held in your hand to the chat.",
    "showkit": "Show contents of a kit.",
    "sions": "Sions Temporal Reconstruction administration and control.",
    "sit": "Duduk santai di lantai atau kursi.",
    "skin": "Changes your own skin.",
    "skins": "Opens the skins GUI.",
    "skript": "Skript's main command. Type '/skript help' for more information.",
    "skull": "Gives you a skull.",
    "slay": "[player] - Slay a player",
    "smithingtable": "Opens up a smithing table.",
    "snapshot": "Snapshot commands for restoring backups",
    "snow": "Simulates snow",
    "socialspy": "Toggles if you can see msg/mail commands in chat.",
    "sort": "Rapikan & gabungkan isi peti/tong yang sedang dibuka.",
    "spark": "",
    "spawn": "Teleports to the spawn point.",
    "spawner": "Change the mob type of a spawner.",
    "spawnmob": "Spawns a mob.",
    "spawnpoint": "A Mojang provided command.",
    "spectate": "A Mojang provided command.",
    "speed": "Change your speed limits.",
    "spigot": "Spigot related commands",
    "spreadplayers": "A Mojang provided command.",
    "sr": "Admin commands for SkinsRestorer.",
    "staffchat": "Speak in Staff chat channel.",
    "stonecutter": "Opens up a stonecutter.",
    "stop": "A Mojang provided command.",
    "stopfire": "[<world>] - Disables all fire spread temporarily",
    "stopsound": "A Mojang provided command.",
    "stopwatch": "A Mojang provided command.",
    "sudo": "Make another user perform a command.",
    "suicide": "Causes you to perish.",
    "summon": "A Mojang provided command.",
    "superpickaxe": "Super-pickaxe commands",
    "swing": "A Mojang provided command.",
    "sync": "Synchronize player profile, balances, and BattlePass with web platform.",
    "tab": "Plugin's main command",
    "team": "A Mojang provided command.",
    "teammsg": "A Mojang provided command.",
    "tellraw": "A Mojang provided command.",
    "tempban": "Temporary ban a user.",
    "tempbanip": "Temporarily ban an IP Address.",
    "template": "Template commands",
    "test": "A Mojang provided command.",
    "thaw": "Thaws the area",
    "thru": "Pass through walls",
    "thunder": "Enable/disable thunder.",
    "tick": "A Mojang provided command.",
    "time": "Display/Change the world time. Defaults to current world.",
    "timings": "Manages Spigot Timings data to see performance of the server.",
    "titles": "Open the Title Vault GUI to equip prestige titles and honorific badges.",
    "tm": "A Mojang provided command.",
    "toggleeditwand": "Remind the user that the wand is now a tool and can be unbound with /tool none.",
    "togglejail": "Jails/Unjails a player, TPs them to the jail specified.",
    "toggleplace": "Switch between your position and pos1 for placement",
    "tool": "Binds a tool to the item in your hand",
    "top": "Teleport to the highest block at your current position.",
    "totp": "TOTP commands",
    "tp": "Teleport to a player.",
    "tpa": "Request to teleport to the specified player.",
    "tpaall": "Requests all players online to teleport to you.",
    "tpacancel": "Cancel all outstanding teleport requests. Specify [player] to cancel requests with them.",
    "tpaccept": "Accepts teleport requests.",
    "tpahere": "Request that the specified player teleport to you.",
    "tpall": "Teleport all online players to another player.",
    "tpauto": "Automatically accept teleportation requests.",
    "tpdeny": "Rejects teleport requests.",
    "tphere": "Teleport a player to you.",
    "tpo": "Teleport override for tptoggle.",
    "tpoffline": "Teleport to a player's last known logout location",
    "tpohere": "Teleport here override for tptoggle.",
    "tppos": "Teleport to coordinates.",
    "tpr": "Teleport randomly.",
    "tps": "Gets the current ticks per second for the server",
    "tptoggle": "Blocks all forms of teleportation.",
    "tracemask": "Set the mask used to stop tool traces",
    "trade": "Trade items and currency with another player",
    "trait": "Trait commands",
    "tree": "Tree generator tool",
    "trigger": "A Mojang provided command.",
    "trust": "Trust a player in your claimed lands.",
    "unban": "Unbans the specified player.",
    "unbanip": "Unbans the specified IP address.",
    "unclaim": "Unclaim the current chunk.",
    "undo": "Undoes the last action (from history)",
    "ungod": "[player] - Disable godmode on a player",
    "unlimited": "Allows the unlimited placing of items.",
    "unlinkaccount": "Unlink your Java account from your Bedrock account",
    "unregister": "Unregister an account",
    "unstuck": "Escape from being stuck inside a block",
    "untrust": "Revoke trust from a player in your claimed lands.",
    "up": "Go upwards some distance",
    "v": "Shortcut for /vanish.",
    "vanish": "Hide yourself from other players.",
    "vault": "Membuka Fishing Vault brankas penyimpanan hasil pancingan",
    "ver": "Gets the version of this server including any plugins in use",
    "verification": "Verification command",
    "version": "Gets the version of this server including any plugins in use",
    "viaversion": "Shows ViaVersion Version and more.",
    "voicechat": "Manage voice chat",
    "vote": "Dukung kedaulatan server Apexsions dan klaim imbalan Vote Keys serta saldo.",
    "warp": "List all warps or warp to the specified location.",
    "warpinfo": "Finds location information for a specified warp.",
    "warpmgr": "Open interactive Admin Warp Management GUI.",
    "warps": "Open the interactive warp navigation menu.",
    "waypoint": "A Mojang provided command.",
    "waypoints": "Waypoint commands",
    "weather": "Sets the weather.",
    "whitelist": "A Mojang provided command.",
    "whois": "Determine basic information about the specified player.",
    "wild": "Random teleport strictly inside your pledged kingdom territory.",
    "workbench": "Opens up a workbench.",
    "worldborder": "A Mojang provided command.",
    "worldedit": "WorldEdit commands",
    "worldguard": "WorldGuard commands",
    "worth": "Calculates the worth of items in hand or as specified."
}
